name: dnd_order_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_rating_bar: ^4.0.1

  google_maps_flutter: ^2.2.6

  get: ^4.6.5

  iamport_flutter: ^0.10.0

  flutter_secure_storage: ^8.0.0
  firebase_auth: ^4.6.2
  kakao_flutter_sdk: ^1.4.1 # 전체 추가
  dio: ^5.2.0+1
  kpostal: ^0.5.1
  http: ^0.13.6
  flutter_neumorphic: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login/
